### ISSUE TITLE
Finish README

### ISSUE THREAD

**Issue by ivan8i** [ivan8i/hello-world#1]
# Sample Readme :boom:

Squirty cheese rubber cheese cheese triangles. Hard cheese _monterey_ jack babybel fromage dolcelatte stilton blue **castello** say cheese. Ricotta jarlsberg cheese strings chalk and cheese chalk and cheese cheese slices pepper jack cheddar. Bocconcini <del>boursin</del> cut the cheese fromage.
#### Blockquote

> Coffee. The finest organic suspension ever devised... I beat the Borg with it. 
> - Captain Janeway
## List
- List item 1
- List item 2
  - List item 2-1
  - List item 2-2
    - List item 2-2-1
  - List item 2-3
- List item 3
- List item 4
## Task
- [x] @mentions, #refs, [links](), **formatting**, and <del>tags</del> supported
- [x] list syntax required (_any unordered or ordered list supported_)
- [x] this is a complete item
- [x] this is an incomplete item
## Table

| First Header | Second Header |
| --- | --- |
| Content from cell 1 | Content from cell 2 |
| Content in the first column | Content in the second column |
## Code

``` javascript
    if (isAwesome){
      return true
    }
```
